apiVersion: batch/v1
kind: Job
metadata:
  name: spark-on-eks
spec:
  template:
    spec:
      containers:
        - name: spark
          image: ashwinijindal10/spark-code:latest
          command: [
            "/bin/sh",
            "-c",
            "/opt/spark/bin/spark-submit \
            --master k8s://http://127.0.0.1:6443 \   
            --deploy-mode cluster \
            --name spark-on-eks \
            --conf spark.executor.instances=2 \
            --conf spark.executor.memory=1G \
            --conf spark.executor.cores=1 \
            --conf spark.kubernetes.container.image=ashwinijindal10/spark-code:latest \
            --conf spark.kubernetes.container.image.pullPolicy=Always \
            --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
            --conf spark.kubernetes.pyspark.pythonVersion=3 \
            --conf spark.jars.ivy=/tmp/.ivy2 \
            local:///opt/jobs/etl_job.py"
          ]
      serviceAccountName: spark
      restartPolicy: Never
  backoffLimit: 4